version: "3.7"
name: pizzashop

services:
  pg:
    image: bitnami/postgresql:17.2.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pizzashop
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
